# OAuth2 Listener
listen: ":7890"

# Matrix authentication
# The Matrix homeserver to connect to
homeserver: https://matrix.example.com
# The Matrix username of the help bot
username: "@help:example.com"
# A file containing the Matrix user password. The password can also be
# specified via the MEETBOT_PASSWORD environment variable.
password_file: /path/to/password/file
# The display name to set for the bot.
displayname: Google Meet
# The avatar to set for the bot.
avatar_url: mxc://nevarro.space/EQldsaNpqiGPJCatXiLeUTIb

# Database configuration
database:
  # The database type. Only "sqlite3-fk-wal" is supported.
  type: sqlite3-fk-wal
  # The database URI.
  #   SQLite: A raw file path is supported, but `file:<path>?_txlock=immediate` is recommended.
  #           https://github.com/mattn/go-sqlite3#connection-string
  uri: file:./meetbot.db?_txlock=immediate
  # Maximum number of connections. Mostly relevant for Postgres.
  max_open_conns: 20
  max_idle_conns: 2
  # Maximum connection idle time and lifetime before they're closed. Disabled if null.
  # Parsed with https://pkg.go.dev/time#ParseDuration
  max_conn_idle_time: null
  max_conn_lifetime: null

# Logging configuration
# See https://github.com/tulir/zeroconfig
logging:
  writers:
    - type: stderr
      format: pretty-colored

# Google Calendar credentials JSON. This value can also be specified via the
# MEETBOT_GOOGLE_CREDENTIALS_JSON environment variable.
google_credentials_json:
